export const toggleTheme = {
    TOGGLE_THEME_LOADING: "TOGGLE_THEME_LOADING",
    TOGGLE_THEME_ACTION: "TOGGLE_THEME_ACTION",
    SET_TOGGLE_THEME: "SET_TOGGLE_THEME"
}

export const authConstants = {
    AUTH_LOADING: "AUTH_LOADING",

    REGISTER_ACTION: "REGISTER_ACTION",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR",
    RESET_REGISTER: "RESET_REGISTER",

    LOGIN_ACTION: "LOGIN_ACTION",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    RESET_LOGIN: "RESET_LOGIN",

    REFRESH_TOKEN_ACTION: "REFRESH_TOKEN_ACTION",
    REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
    REFRESH_TOKEN_ERROR: "REFRESH_TOKEN_ERROR"
};

export const userConstants = {
    USER_LOADING: "USER_LOADING",
    USER_ACTION: "USER_ACTION",
    USER_SUCCESS: "USER_SUCCESS",
    USER_ERROR: "USER_ERROR",
    USER_RESET: "USER_RESET",
}